---
- name: Deploy Docker Container
  hosts: docker_servers
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: nginx
        state: present

    - name: Run Docker container
      docker_container:
        name: my-nginx
        image: nginx
        ports:
          - "80:80"
