---
- name: Provision Web Server
  hosts: web_servers
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Deploy a sample HTML page
      copy:
        src: index.html
        dest: /var/www/html/